env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'prettier/@typescript-eslint'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  react/prop-types:
    - off
  '@typescript-eslint/no-empty-function':
    - off
  '@typescript-eslint/explicit-module-boundary-types':
    - off
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
  'react/jsx-fragments':
    - error
    - element
settings:
  react:
    version: detect
