name: publish
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  publish-gh-pages:
    name: mainリポジトリ更新時にGithub Pagesへ公開
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: gh-pages
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: yarn
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - env:
          REACT_APP_GA_MEASUREMENT_ID: G-4ZNXNCE4SW
        run: |
          git config --global user.name "YuhSylphy"
          git config --global user.email "yuhsylphy@gmail.com"
          git switch -C gh-pages origin/gh-pages
          git merge --no-ff -X theirs origin/main
          if ! git diff --exit-code --quiet @..@^1 -- src/* ./*.json ./*.md; then
            echo REACT_APP_GA_MEASUREMENT_ID=G-4ZNXNCE4SW > .env.prod
            yarn --network-timeout=1000000
            yarn build
            yarn cpx -C 'build/**' './docs/'
            git add docs/
            git commit -m "Rebuild docs by Actions"
          elif ! git diff --exit-code --quiet @..@^1 -- ./public/assets/*; then
            yarn --network-timeout=1000000
            yarn cpx -C './public/assets/**' './docs/assets/'
            git add docs/
            git commit -m "apply assets to docs by Actions"
          else
            echo nothing to build.
          fi
          git push origin gh-pages
